### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [lindatablerosgessner/cdmx-2018-06-bc-core-am-data-dashboard#1]
Hola @lindatablerosgessner y @LexHernandez 
He estado revisando el proyecto y tengo algunos comentarios:

1. Veo que no realizaron los issues y milestones correspondientes al sprint 2 del proyecto, que pasó con eso?

2. En el **readme.md** que tienen dentro de **src** al final tienen un conflicto no solucionado, lo puedo ver porque los signos `<<<<<<< HEAD ========` lo muestran.

3. Les recomiendo comenzar a trabajar con la data lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

4. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

5. Ojo con el trabajo colaborativo en github, solo veo commits de @lindatablerosgessner

6. No olviden desarrollar desde los tests, tomense el tiempo de analizar que pide el test y desde ahí será mucho más sencillo la estructura a desarrollar 

Vamos con todo el power en honor al tiempo que nos va quedando para desarrollar el datadashboard :muscle: :rocket:

**Comment by cltg** [comment]
Gracias por tus issues @nerdale, ¡vamos a meterle velocidad este fin de semana! :)

**Comment by nerdale** [comment]
Daré por cerrado el issue :smile: 
:rocket:
